name: MineFightWeapons
version: 0.0.1
description:
author: Tobias Schramm 'Toble_Miner'
website:
depend: [MineFight]
softdepend: [MineFight]
database: false

main: TobleMiner.MineFightWeapons.Main

commands:

permissions:
